### ISSUE TITLE
Download from get.jenkins.io instead of archives.jenkins.io

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/pipeline-steps-doc-generator#400]
### What feature do you want to see added?

The Pipeline steps doc generator downloads all the plugin binary files for analysis.  It downloads from archives.jenkins.io as seen in the [console log of the job on ci.jenkins.io](https://ci.jenkins.io/job/Infra/job/pipeline-steps-doc-generator/job/master/lastBuild/console).  It would perform better and be more portable if it downloaded the plugins from get.jenkins.io instead of archives.jenkins.io

### Upstream changes

N/A

**Comment by kesrishubham2510** [comment]
Hi @MarkEWaite, I'm new to the open source ecosystem and would like to contribute to this good-first-issue.

<img width="657" alt="Screenshot 2024-09-22 at 02 02 39" src="https://github.com/user-attachments/assets/efb6106b-8373-4776-900f-b06894016828">

I checked the logs on the attached link, I didn't see 'archives.jenkins.io' logged in the logs. I have attached a screenshot for the reference.

Please let me know, if this issue is relevant

**Comment by MarkEWaite** [comment]
Thanks for asking @kesrishubham2510 .  You're correct that the console log of the Jenkins job no longer reports the download source (whether archives.jenkins.io or get.jenkins.io).  I don't yet know if this issue is still relevant.

I need to explore the build process again in order to understand why the following pull request is failing:

* #485 

During the exploration of that failure, I should be able to find an answer to the question.
